### ISSUE TITLE
Time zone issue with actual times.

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/github-action-start-standard-change#29]
Looks like the time zones aren't matching up in the "Planned" and "Actual" fields. Planned seems to be MDT and Actual seems to be UTC.

<img width="1016" alt="Screen Shot 2021-08-06 at 7 59 24 AM" src="https://user-images.githubusercontent.com/9389424/128521648-5aaf424a-4237-442f-bcef-0e8122993820.png">

**Comment by GaryGSC** [comment]
Nothing should need to change in this action, so see the referenced issue for updates.
